### ISSUE TITLE
Install containerd instead of docker

### ISSUE THREAD

**Issue by rkevin-arch** [LibreTexts/protogalaxy#2]
Kubernetes 1.20 will [drop support for using Docker as a container runtime](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/). This shouldn't be a cause for concern, since Docker uses containerd under the hood anyway, and containerd is supported by Kubernetes. We can keep Docker installed, and that should be fine, but we should just install containerd itself and ditch the Docker layer.

Our workflow shouldn't really change, as Docker images are mostly CRI compliant, so any images built with Docker would still run. We do need to teach people how to use `crictl` instead of `docker` commands, though, to investigate running containers on nodes.

The only thing I can think of that might break is binder, which uses repo2docker. Depending on how repo2docker builds images (whether it uses `/var/run/docker.sock` to build the image), it might break. TODO: do more research and make sure this isn't a problem.

Also, TODO: Investigate CRI-O, which is a replacement for containerd, and whether we should use that instead of containerd.

Other further reading: https://kubernetes.io/blog/2020/12/02/dockershim-faq/

**Comment by rkevin-arch** [comment]
CRI-O seems to be designed purely for use with Kubernetes. One thing I don't like is how it [doesn't have a CLI tool for interacting with containers](https://github.com/cri-o/cri-o#what-is-not-in-scope-for-this-project), which means everything must be done through kubectl. Since I used `docker exec -itu0` to force run commands as root in a container for debugging purposes, I'm not sure if having no CLI tool is a good idea (I guess we can use `runc` and operate on the container directly, maybe?)

On the other hand, containerd is mostly a drop-in replacement for docker, since docker uses containerd under the hood anyway, and it is probably a smoother transition. I'd like to get some other people's opinions first, though.

**Comment by moorepants** [comment]
Thanks for opening this. I saw this news today too. Given that binder is often deployed with kubernetes I would expect the Jupyter team to have to address this there too.

**Comment by rkevin-arch** [comment]
Re: binder, https://binderhub.readthedocs.io/en/latest/zero-to-binderhub/setup-binderhub.html#use-docker-inside-docker-dind might get rid of this issue. Need to test on Galaxy once we remove docker altogether.

**Comment by rkevin-arch** [comment]
Apparantly `crictl` is not containerd-specific, it works on both containerd and CRI-O, so I take back my comment about CRI-O not having a CLI tool for debugging purposes.

**Comment by rkevin-arch** [comment]
Some local testing using a tool called [bucketbench](https://github.com/estesp/bucketbench):
```
rkevin@redshift:~$ sudo systemctl start docker containerd crio
[sudo] password for rkevin: 
rkevin@redshift:~$ cd libretexts/bucketbench/
rkevin@redshift:~/libretexts/bucketbench$ sudo docker version
Client:
 Version:           19.03.14-ce
 API version:       1.40
 Go version:        go1.15.5
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 23:20:14 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.14-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.15.5
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 23:14:28 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b.m
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
rkevin@redshift:~/libretexts/bucketbench$ sudo ctr version
Client:
  Version:  v1.4.3
  Revision: 269548fa27e0089a8b8278fc4fc781d7f65a939b.m
  Go version: go1.15.5

Server:
  Version:  v1.4.3
  Revision: 269548fa27e0089a8b8278fc4fc781d7f65a939b.m
  UUID: b2384040-06c1-4377-8740-11ef4768670a
rkevin@redshift:~/libretexts/bucketbench$ sudo crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.19.0
RuntimeApiVersion:  v1alpha1
rkevin@redshift:~/libretexts/bucketbench$ sudo ~/go/bin/bucketbench run -b examples/docker.yaml 

SUMMARY TIMINGS/THREAD RATES

                    Iter/Thd    1 thrd   2 thrds   3 thrds   4 thrds   5 thrds   6 thrds   7 thrds   8 thrds   9 thrds  10 thrds 
             Limit      1000    651.73   3050.96   5266.30   6573.30   7237.50   7846.55   8082.68   8072.32   8084.63   8088.72 
  Custom:DockerCLI        15      1.42      2.46      3.17 

DETAILED COMMAND TIMINGS/STATISTICS

  Custom:DockerCLI:1       Min       Max       Avg    Median    Stddev    Errors
                 run    359.00    433.00    396.33    392.00     23.12         0
                stop    178.00    311.00    236.53    238.00     37.33         0
              delete     50.00     76.00     61.87     61.00      6.81         0
  Custom:DockerCLI:2       Min       Max       Avg    Median    Stddev    Errors
                 run    258.00    660.00    490.27    506.00    106.09         0
                stop    159.00    383.00    245.70    233.00     55.99         0
              delete     31.00    105.00     50.50     45.00     16.01         0
  Custom:DockerCLI:3       Min       Max       Avg    Median    Stddev    Errors
                 run    253.00    785.00    562.07    594.00    139.24         0
                stop    142.00    397.00    274.51    276.00     59.33         0
              delete     34.00    121.00     78.51     83.00     25.53         0
rkevin@redshift:~/libretexts/bucketbench$ sudo ~/go/bin/bucketbench run -b examples/ctrd.yaml 

SUMMARY TIMINGS/THREAD RATES

                     Iter/Thd    1 thrd   2 thrds   3 thrds   4 thrds   5 thrds   6 thrds   7 thrds   8 thrds   9 thrds  10 thrds 
              Limit      1000   1648.20   3528.84   5253.39   6540.84   7177.38   7799.00   7963.04   7944.41   7923.39   7850.84 
  Custom:Containerd        10      8.10     22.76     17.23     22.03     24.81 

DETAILED COMMAND TIMINGS/STATISTICS

  Custom:Containerd:1       Min       Max       Avg    Median    Stddev    Errors
                  run     55.00    191.00     95.40     62.00     48.27         0
                 stop     13.00     40.00     21.70     15.00     11.26         0
               delete      3.00      6.00      4.50      4.00      1.12         0
  Custom:Containerd:2       Min       Max       Avg    Median    Stddev    Errors
                  run     54.00    120.00     64.00     58.00     18.72         0
                 stop     11.00     23.00     16.35     15.50      3.75         0
               delete      3.00      8.00      5.15      5.00      1.39         0
  Custom:Containerd:3       Min       Max       Avg    Median    Stddev    Errors
                  run     88.00    207.00    129.97    118.50     34.71         0
                 stop     18.00     65.00     30.77     28.50     10.54         0
               delete      6.00     33.00     10.17      9.00      6.10         0
  Custom:Containerd:4       Min       Max       Avg    Median    Stddev    Errors
                  run     90.00    227.00    136.93    113.00     43.63         0
                 stop     12.00     56.00     26.73     26.00      6.81         0
               delete      4.00     39.00     12.22     10.00      8.77         0
  Custom:Containerd:5       Min       Max       Avg    Median    Stddev    Errors
                  run     71.00    256.00    153.38    154.00     60.76         0
                 stop     10.00     79.00     26.28     25.00     11.45         0
               delete      3.00     61.00     16.10     11.00     12.75         0
rkevin@redshift:~/libretexts/bucketbench$ sudo ~/go/bin/bucketbench run -b examples/crio.yaml 

SUMMARY TIMINGS/THREAD RATES

              Iter/Thd    1 thrd   2 thrds   3 thrds   4 thrds   5 thrds   6 thrds   7 thrds   8 thrds   9 thrds  10 thrds 
       Limit      1000   1214.12   2941.86   5248.17   6553.31   7203.63   7681.01   7833.54   7823.74   7823.50   7775.10 
  Custom:CRI         1      0.35      0.70      1.07      1.24      1.65 

DETAILED COMMAND TIMINGS/STATISTICS

  Custom:CRI:1       Min       Max       Avg    Median    Stddev    Errors
           run    163.00    163.00    163.00    163.00      0.00         0
          stop    494.00    494.00    494.00    494.00      0.00         0
        delete     38.00     38.00     38.00     38.00      0.00         0
  Custom:CRI:2       Min       Max       Avg    Median    Stddev    Errors
           run     52.00     68.00     60.00     60.00      8.00         0
          stop    301.00    667.00    484.00    484.00    183.00         0
        delete     50.00    100.00     75.00     75.00     25.00         0
  Custom:CRI:3       Min       Max       Avg    Median    Stddev    Errors
           run     79.00     84.00     82.33     84.00      2.36         0
          stop    275.00    540.00    393.67    366.00    109.94         0
        delete     24.00     78.00     53.33     58.00     22.29         0
  Custom:CRI:4       Min       Max       Avg    Median    Stddev    Errors
           run     60.00    116.00     82.00     76.00     20.99         0
          stop    128.00    550.00    259.00    179.00    170.62         0
        delete     25.00     77.00     42.75     34.50     20.40         0
  Custom:CRI:5       Min       Max       Avg    Median    Stddev    Errors
           run    107.00    124.00    112.20    110.00      6.01         0
          stop    195.00    433.00    313.60    289.00     81.90         0
        delete     39.00     90.00     54.80     46.00     18.35         0
```
They are spawning the alpine pod using Docker, containerd and CRI-O, using 3/5/5 threads each. Docker is by far the slowest, and containerd and CRI-O seem to be comparable, with CRI-O being a bit faster when starting containers, and containerd a bit faster when stopping/deleting them (these numbers fluctuate on subsequent tests).

However, during my setup, CRI-O gave me a ton of trouble. I had to mess with the cgroup driver (changed from systemd to cgroupfs back to systemd), mess with the sandbox config, and add a CNI plugin manually (even though I'm running this outside of k8s). These may not be issues with kubernetes, though.

Also, the second time I run the CRI-O benchmark it gives a ton of errors like these:
```
ERRO[0032] Error on creating container "bb-ctr-3-0" from image "docker.io/library/alpine:latest": rpc error: code = Unknown desc = Kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving pod name k8s_podbb-ctr-3-0_bucketbench.test.cri_bucketbench-test-cri_1 for id 786be8ad5ca807cf0922ecb686e0f23929c032431f0d1b7fcc60c45cce0a5a1e: name is reserved 
```
No idea what they are (maybe it's just the benchmark program being shady), but I had to reboot to fix the issue. Sometimes the benchmark can still finish, sometimes it can't.

Finally, the installation instructions for containerd is very simple (add a deb repo, apt update, apt install one package), while the one for CRI-O involves adding two repos (one repo's URL being tied to the CRI-O version, so we can't upgrade without changing the repo) from OpenSUSE. It's a bit clunkier in my opinion. For the above reasons, I'm heavily leaning towards containerd, but I'd like some outside opinions as well. I haven't found any article online that says "here's why you should choose one over the other".

**Comment by rkevin-arch** [comment]
~~Testing containerd on the cluster, everything looks good so far (https://staging.galaxy.rkevin.dev is operating without any issues). Gonna experiment with Binder using dind in a bit.~~ I was actually not testing containerd at all, and when switching to containerd I broke the entire cluster. Fantastic. It might remain unusable for a couple of days, but fortunately that's what dev clusters are for.

**Comment by celine168** [comment]
I've read a bit on the subject.
I'm a bit confused on how we are able to still use Docker or repo2docker if we switch to the CRI-O container runtime. Docker uses containerd, so I can see how switching to that shouldn't cause any problems. The repo2docker "uses" the Docker installed on the machine, so we would have to install Docker on each node anyways, correct?

Definitely support moving to containerd or CRI-O.

You might find this article helpful if you happen to be reading up on this issue: https://medium.com/cri-o/container-runtimes-clarity-342b62172dc3

**Comment by rkevin-arch** [comment]
I saw there's a `dind` option on the binderhub helm chart. The documentation didn't make it super clear what it does, but looking at the chart it seems to run a [DaemonSet](https://github.com/jupyterhub/binderhub/blob/master/helm-chart/binderhub/templates/dind/daemonset.yaml) that runs Docker inside of a container and expose it. I'm not sure if this will 100% fix the issue, which is why we have to test it. (We should also make an issue / PR to binderhub to make the documentation clearer once we test it and it works)

**Comment by rkevin-arch** [comment]
A brief digression into ubuntu autoinstall cloud-init land later, I found out what the problem with containerd is: 
1. The `br_netfilter` kernel module must be loaded.
2. The `net.ipv4.ip_forward` sysctl must be enabled
3. containerd by default installs with a `/etc/containerd/config.toml` with `disabled_plugins = ["cri"]` for whatever reason. Kubernetes tries to talk to containerd using CRI, fails, then refuses to work.

1 and 2 are usually solved by docker, but for some reason containerd doesn't do it automatically. 3 can be fixed by detecting that line and deleting the config if it is present. The default values if the config file does not exist works perfectly.

After all this (and fixing an unrelated issue with nfs-client-provisioner), the cluster seems to function. JupyterHub and Grafana both work. Gonna test Binder in a bit.

**Comment by rkevin-arch** [comment]
Binder does not work, with or without DinD. DinD seems to want to mount the host Docker socket for some reason. This means we cannot use Binder without Docker on the host for now. Gonna mention the same information in metalc because that is going off topic from protogalaxy.

**Comment by Miniland1333** [comment]
> Binder does not work, with or without DinD. DinD seems to want to mount the host Docker socket for some reason. This means we cannot use Binder without Docker on the host for now. Gonna mention the same information in metalc because that is going off topic from protogalaxy.

This may or may not be relevant, but this is from the Kubernetes blog about how this change affects Docker in Docker https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

"One thing to note: If you are relying on the underlying docker socket (/var/run/docker.sock) as part of a workflow within your cluster today, moving to a different runtime will break your ability to use it. This pattern is often called Docker in Docker. There are lots of options out there for this specific use case including things like [kaniko](https://github.com/GoogleContainerTools/kaniko), [img](https://github.com/genuinetools/img), and [buildah](https://github.com/containers/buildah)."

**Comment by rkevin-arch** [comment]
Yeah, that's why Binder doesn't work. I'll look into whether we can still run dind in containerd (it sort of seems like it, would make a decent temporary solution) and how to port repo2docker to use another build system.
